# 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号，在沙箱应用中获取
alipay.appId=
# 商户PID 2088621993909206
alipay.seller-id=
# 商户私钥，您的PKCS8格式RSA2私钥，通过开发助手生成的应用私钥
alipay.privateKey=
alipay.publicKey=B

# 对称密钥 ==
alipay.content-AESkey=
# 服务器异步通知页面路径需http://格式的完整路径，不能加?id=123这类自定义参数
alipay.notifyUrl=
# 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数
alipay.returnUrl=http://localhost:3000/course/
# 签名方式
alipay.signType=RSA2
# 字符编码格式
alipay.charset=utf-8
# 支付宝网关，在沙箱应用中获取
# https://openapi.alipaydev.com/gateway.do
alipay.gatewayUrl=https://openapi.alipaydev.com/gateway.do
